language: rust
branches:
  only:
    - auto
    - master

rust:
  - stable
  - beta
  - nightly

notifications:
  irc: 'irc.freenode.org#cryptosphere'
  webhooks: http://iqulus.cryptosphere.org:10103/travis
