language: rust
sudo: false

before_script:
    rustup update

branches:
  only:
    - master

rust:
  - nightly

os:
  - linux
  - osx

matrix:
  fast_finish: true

notifications:
  irc: 'irc.freenode.org#cryptosphere'
