language: rust
sudo: false

branches:
  only:
    - master

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

notifications:
  irc: 'irc.freenode.org#cryptosphere'
