language: rust
sudo: false

script: cargo test --verbose --release

branches:
  only:
    - master

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

notifications:
  irc: 'irc.freenode.org#cryptosphere'
