[package]
name        = "ithos"
description = "Modern directory services and credential management"
homepage    = "https://github.com/cryptosphere/ithos"
repository  = "https://github.com/cryptosphere/ithos"
readme      = "README.md"
keywords    = ["directory", "identity", "access", "credentials"]
license     = "Apache-2.0"
version     = "0.0.0"
authors     = ["Tony Arcieri <bascule@gmail.com>"]

[dependencies]
time = ">= 0.1.35"
lmdb = ">= 0.5.0"
lmdb-sys = ">= 0.5.0"
clap = "2"

[dependencies.ring]
git = "https://github.com/briansmith/ring"

[dev-dependencies]
tempdir = "0.3"
