[package]
name        = "ithos"
description = "Modern directory services and credential management"
homepage    = "https://github.com/cryptosphere/ithos"
repository  = "https://github.com/cryptosphere/ithos"
readme      = "README.md"
keywords    = ["directory", "identity", "access", "secrets", "ldap"]
license     = "Apache-2.0"
version     = "0.0.0"
authors     = ["Tony Arcieri <bascule@gmail.com>"]

[dependencies]
clap            = "^2.20"
lmdb            = ">= 0.5.0"
lmdb-sys        = ">= 0.5.0"
protobuf        = "^1.0"
rustc-serialize = ">= 0.3.19"
ring            = ">= 0.2.3"
ring-pwhash     = ">= 0.1.0"
rpassword       = ">= 0.3"
time            = ">= 0.1.35"

[dependencies.objecthash]
git = "https://github.com/cryptosphere/objecthash-rs.git"
features = ["octet-strings"]

[dev-dependencies]
tempdir = ">= 0.3"
