[package]
name        = "ithos"
description = "Modern directory services and credential management"
homepage    = "https://github.com/cryptosphere/ithos"
repository  = "https://github.com/cryptosphere/ithos"
readme      = "README.md"
keywords    = ["directory", "identity", "access", "credentials"]
license     = "Apache-2.0"
version     = "0.0.0"
authors     = ["Tony Arcieri <bascule@gmail.com>"]

[dependencies]
clap            = "2"
lmdb            = ">= 0.5.0"
lmdb-sys        = ">= 0.5.0"
serde_json      = "0.8"
rustc-serialize = ">= 0.3.19"
time            = ">= 0.1.35"

[dependencies.buffoon]
git = "https://github.com/carllerche/buffoon.git"

[dependencies.ring]
git = "https://github.com/briansmith/ring"

[dependencies.ring-pwhash]
git = "https://github.com/cryptosphere/ring-pwhash"

[dev-dependencies]
tempdir = "0.3"
